# Generated by Django 4.1.7 on 2023-03-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_facility_photo_event_application_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_application',
            new_name='EventApplication',
        ),
    ]
