# Generated by Django 4.1.7 on 2023-03-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_current_paticipants_event_current_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.event'),
        ),
    ]
