# Generated by Django 4.1.7 on 2023-03-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_eventapplication_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationframe',
            name='stripe_product_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prices', to='booking.reservationframe')),
            ],
        ),
    ]
